name: Run docker compose

on: 
    push

jobs:
    docker-compose:
        runs-on: self-hosted
        steps:
        -   name: Checkout repo
            uses: actions/checkout@v4

        -   name: change directory
            run: cd flask-redis

        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: aman3105
                password: dOC@MAN3105

        -   name: check for dockerfile
            run: |
                ls -la
                pwd
                
        -   name: Build and push
            uses: docker/build-push-action@v5
            with:
                push: true
                tags: aman3105/flask-redis:latest

        -   name: Execute docker compose
            run: docker compose up -d
